[green_agent]
agentbeats_id = "019bb88c-099e-7e73-93c8-d17e7a59866a"
env = {
    NEBIUS_API_KEY = "${NEBIUS_API_KEY}",
    LOG_LEVEL = "INFO",
    provider = "nebius",
    SERPAPI_API_KEY = "${SERPAPI_API_KEY}",
    EDGAR_API_KEY = "${EDGAR_API_KEY}"
}

[[participants]]
agentbeats_id = ""
name = "purple_agent"
env = {}

[config]
# Query type from this options:
# - Quantitative Retrieval
# - Qualitative Retrieval
# - Numerical Reasoning
# - Complex Retrieval
# - Adjustments
# - Beat or Miss
# - Trends
# - Financial Modeling
# - Market Analysis
#
# Or all otherwise
type = ""

# For specific index in question type
query_index = ""
