[green_agent]
agentbeats_id = "019bb88c-099e-7e73-93c8-d17e7a59866a"
env = { NEBIUS_API_KEY = "${NEBIUS_API_KEY}", LOG_LEVEL = "INFO", MODEL_PROVIDER = "nebius", SERPAPI_API_KEY = "${SERPAPI_API_KEY}", EDGAR_API_KEY = "${EDGAR_API_KEY}"}

[[participants]]
agentbeats_id = "019bb8a1-d7fe-72f1-82c2-4e2bf595e642"
name = "purple_agent"
env = { NEBIUS_API_KEY = "${NEBIUS_API_KEY}", MCP_SERVER =  "http://green-agent:9020", MODEL_NAME="NousResearch/Hermes-4-405B"}

[config]
# Query type from this options:
# - Quantitative Retrieval
# - Qualitative Retrieval
# - Numerical Reasoning
# - Complex Retrieval
# - Adjustments
# - Beat or Miss
# - Trends
# - Financial Modeling
# - Market Analysis
#
# Or all otherwise
type = "Adjustments"

# For specific index in question type (comment for whole set)
# query_index = "3"
